///////////////////////////////////////////////////////////
//  CUAbmRelacion.cs
//  Clase de implementación de CUAbmRelacion.
//  Generated by Fito
//  Created on:      08-abr-2009 11:32:54
//  Original author: Fito
///////////////////////////////////////////////////////////
using scioBaseLibrary.excepciones;
using scioControlLibrary;
using scioToolLibrary;
using sgmpro.dominio.configuracion;

namespace cuAbmRelacion {
    /// <summary>
    /// Esta clase hereda de CUAbmGenerico y se encarga de gestionar la 
    /// ventana WinABMV junto con su panelABMV para la entidad Relacion.
    /// </summary>
    public class CUAbmRelacion : CUAbmGenerico<Relacion> {
        #region IControladorEditable Members
        /// <summary>
        /// Implementación del método de la interfaz.
        /// </summary>
        public override PanelABMV<Relacion> crearPanelEdicion() {
            return new PanelAbmvRelacion(this);
        }

        /// <summary>
        /// Implementación del método de la interfaz.
        /// </summary>
        public override void add(params object[] parametros) {
            if (parametros[0] is Persona)
                ObjetoEnEdicion = new Relacion {Origen = (Persona)parametros[0]};
            else
                throw new AppErrorException("ERROR-ADD-WITHOUT-MASTER", "RELACION");
        }

        /// <summary>
        /// Implementación del método de la interfaz.
        /// </summary>
        public override void verify(params object[] parametros) {
            if (ObjetoEnEdicion.Destino.Id.Equals(ObjetoEnEdicion.Origen.Id))
                throw new DataErrorException("CAMPO-NOK", Mensaje.TextoValidacion("RELACION-PERSONAS"));
        }
        #endregion
    }
}