///////////////////////////////////////////////////////////
//  CUListVariables.cs
//  Clase de implementación de CUListVariables.
//  Generated by Fito
//  Created on:      08-abr-2009 11:32:54
//  Original author: Fito
///////////////////////////////////////////////////////////
using scioControlLibrary;
using scioPersistentLibrary.orden;
using sgmpro.dominio.configuracion;

namespace cuAbmVariable {
    /// <summary>
    /// Esta clase hereda de CUListGenerico y se encarga de 
    /// gestionar un PanelListABMV para la entidad Variable.
    /// </summary>
    public class CUListVariables : CUPreviewGenerico<Variable> {
        /// <summary>
        /// Constructor de la clase que inicializa elementos internos.
        /// </summary>
        public CUListVariables() {
            ControlEditable = new CUAbmVariable();
            Ordenamiento.Add(Orden.Asc("Nombre"));
        }

        #region IControladorListable Members
        // <summary>
        /// Implementación del método de la interfaz.
        /// </summary>
        protected override PanelPreview<Variable> crearPanelPreview() {
            return new PanelPreviewVariable(ControlEditable);
        }
        #endregion
    }
}