///////////////////////////////////////////////////////////
//  CUConfigurarGestion.cs
//  Clase de control para la ventana de configurar gestión.
//  Generated by Fito
//  Created on:      08-abr-2009 11:32:54
//  Original author: Fito
///////////////////////////////////////////////////////////
using scioControlLibrary;

namespace cuConfigurarGestion {
    public class CUConfigurarGestion : CUConfigurarGenerico<ConfigurarGestionTree> {}
}