///////////////////////////////////////////////////////////
//  EstadosCuenta.cs
//  Implementation of the Class EstadosCuenta
//  Generated by Enterprise Architect
//  Created on:      13-May-2009 03:55:00 p.m.
//  Original author: Fito
///////////////////////////////////////////////////////////
using System.Collections.Generic;
using scioPersistentLibrary.acceso;
using scioPersistentLibrary.criterios;
using scioPersistentLibrary.orden;
using sgmpro.dominio.configuracion;

namespace sgmpro.dominio.gestion.repos {
    /// <summary>
    ///   Esta clase representa al Repositorio de persistencia
    ///   de Nhibernate para la entidad Movimiento de Cta Cte 
    ///   (Deuda) del sistema.
    /// </summary>
    public class EstadosCuenta : RepositorioPersistente<EstadoCuenta> {
        /// <summary>
        ///   Este método devuelve un listado de EstadosCuenta según la 
        ///   cuenta que ha sido contactada en las mismas y trayendo primero 
        ///   los EstadosCuenta mas recientes.
        /// </summary>
        /// <param name = "cuenta">
        ///   La cuenta para la que se desea la Lista de EstadosCuenta.
        /// </param>
        /// <returns>
        ///   El Listado de EstadosCuenta de la cuenta deseada ordenados por
        ///   fecha de inicio en forma descendente (primero la ultima).
        /// </returns>
        public static IList<EstadoCuenta> GetByCuentaPorFechaDesc(Cuenta cuenta) {
            return GetByCriteria(
                true,
                new[] {Criterios.Igual("Cuenta", cuenta)},
                new[] {Orden.Desc("FechaInicio")});
        }
    }
}