///////////////////////////////////////////////////////////
//  AppErrorException.cs
//  Implementation of the Class AppErrorException
//  Generated by Enterprise Architect
//  Created on:      14-abr-2009 19:39:46
//  Original author: Fito
///////////////////////////////////////////////////////////
namespace scioBaseLibrary.excepciones {
    /// <summary>
    /// Esta clase de excepción debe utilizarse para representar todos
    /// los errores asociados a un problema de con la aplicación misma,
    /// pero que no resulta en un error fatal para el sistema.
    /// </summary>
    public class AppErrorException : SistemaErrorException {
        public AppErrorException(string mensaje) : base(mensaje) {}
        public AppErrorException(string mensaje, string extra) : base(mensaje, extra) {}
    }
}