///////////////////////////////////////////////////////////
//  VistaErrorException.cs
//  Implementation of the Class VistaErrorException
//  Generated by Enterprise Architect
//  Created on:      14-abr-2009 19:39:46
//  Original author: Fito
///////////////////////////////////////////////////////////
namespace scioBaseLibrary.excepciones {
    /// <summary>
    /// Esta clase de excepción debe utilizarse para representar todos
    /// los errores asociados a un problema con alguna ventana o algún 
    /// componente gráfico del sistema.
    /// </summary>
    public class VistaErrorException : SistemaErrorException {
        public VistaErrorException(string mensaje) : base(mensaje) {}
        public VistaErrorException(string mensaje, string extra) : base(mensaje, extra) {}
    }
}