///////////////////////////////////////////////////////////
//  ICriterioConsulta.cs
//  Implementation of the Interface ICriterioConsulta
//  Generated by Enterprise Architect
//  Created on:      15-Dic-2009 07:11:10 p.m.
//  Original author: Fito
///////////////////////////////////////////////////////////
using NHibernate.Criterion;

namespace scioPersistentLibrary.interfases {
    /// <summary>
    /// Esta interfase define el comportamiento deseable de una clase que 
    /// represente un criterio de consulta que pueda aplicarse como filtro
    /// de una consulta de selección contra el motor de persistencia. Esta 
    /// interfase actúa entonces como cara pública de una capa de abstracción 
    /// de la forma en que el mecanismo de persistencia realiza las consultas
    /// al motor de persistencia, permitiendo, por ejemplo, utilizar consultas 
    /// SQL u otras de interfaces Criteria de mecanismos ORM, y permitiendo 
    /// así accesos tanto relacionales como de objetos.
    /// </summary>
    public interface ICriterioConsulta : IElementoConsulta {
        /// <summary>
        /// Este método debe devolver el criterio contenido como un string 
        /// que pueda adozarse a, un componente where de, una cláusula SQL 
        /// relacional de manera "atómica" (es decir sin interferir con lo
        /// que ya pudiera haber dentro del componente).
        /// </summary>
        /// <returns>
        /// Una cadena con un pedazo de where sin la palabra clave WHERE.
        /// </returns>
        string getCriterioSQL();

        /// <summary>
        /// Este método debe devolver el criterio contenido como un string 
        /// que pueda adozarse a, un componente where de, una cláusula SQL 
        /// relacional de manera "atómica" (es decir sin interferir con lo
        /// que ya pudiera haber dentro del componente). Se diferencia de 
        /// su sobrecarga en que estem método acepta un prefijo para el
        /// armado del nombre de los campos del select.
        /// </summary>
        /// <param name="prefijo">
        /// El prefijo de la tabla para el armado del nombre de los campos 
        /// del select.
        /// </param>
        /// <returns>
        /// Una cadena con un pedazo de where sin la palabra clave WHERE.
        /// </returns>
        string getCriterioSQL(string prefijo);

        /// <summary>
        /// Este método debe devolver un criterio de NHibernate, es decir
        /// un objeto ICriterion que pueda agrgarse a una consulta propia
        /// de NHibernate (un ICriteria).
        /// </summary>
        /// <returns>
        /// Una objeto ICriterion con un criterio de consulta.
        /// </returns>
        ICriterion getCriterioNH();
    }
}
