///////////////////////////////////////////////////////////
//  ItemFactura.cs
//  Implementation of the Class ItemFactura
//  Generated by Enterprise Architect
//  Created on:      13-May-2009 03:54:59 p.m.
//  Original author: Fernando
///////////////////////////////////////////////////////////
using scioBaseLibrary.excepciones;
using scioPersistentLibrary.acceso;

namespace sgmpro.dominio.caja {
    /// <summary>
    /// Esta clase representa una línea de una factura, es decir item 
    /// facturado que se cobra dentro de la misma. A hoy, una factura 
    /// no puede eliminarse ni 'reavivarse'. Esta clase es persistente.
    /// </summary>
    public class ItemFactura : EntidadIdentificada<ItemFactura> {
        /// <summary>
        /// La factura a la que pertenece este item. No nulo. FK.
        /// </summary>
        public virtual Factura Factura { get; set; }
        /// <summary>
        /// El numero de item de factura (orden). No Nulo.
        /// </summary>
        public virtual long Numero { get; set; }
        /// <summary>
        /// El concepto de item de factura (descripcion del item). No Nulo.
        /// </summary>
        public virtual string Concepto { get; set; }
        /// <summary>
        /// El precio del item. Parámetro. No Nulo. 
        /// </summary>
        public virtual double Precio { get; set; }
        /// <summary>
        /// Precio total del item. No es persistente.
        /// </summary>
        public virtual double Total {
            get { return Numero*Precio; }
        }

        /// <summary>
        /// Este método evita que se desborre (o reavive) un recibo.
        /// </summary>
        public override void undelete() {
            throw new DataErrorException("DATA-UNDEL-NOK");
        }

        /// <summary>
        /// Este método genera el string por defecto a mostrar en todos lados.
        /// </summary>
        public override string ToString() {
            return string.Format("{0} ({1})", Numero, Factura);
        }
    }
}