///////////////////////////////////////////////////////////
//  IMensajeHelper.cs
//  Implementation of the Interface IMensajeHelper
//  Generated by Enterprise Architect
//  Created on:      10-Ene-2010 08:11:10 a.m.
//  Original author: Fito
///////////////////////////////////////////////////////////
namespace scioToolLibrary.interfases {
    /// <summary>
    /// Esta interfaz permite generar clases que 'ayuden' a la clase Mensaje
    /// extendiendo la cantidad de mensajes a mostrar. La clase Mensaje tiene
    /// un atributo con el cual trabajar para agregar mensajes personalizados.
    /// </summary>
    public interface IMensajeHelper {
        /// <summary>
        /// Para extender al método homónimo de la clase Mensaje.
        /// </summary>
        string textoMensaje(string mensaje);

        /// <summary>
        /// Para extender al método homónimo de la clase Mensaje.
        /// </summary>
        string textoMensajeConTerminador(string mensaje);

        /// <summary>
        /// Para extender al método homónimo de la clase Mensaje.
        /// </summary>
        string textoValidacion(string mensaje);
    }
}