///////////////////////////////////////////////////////////
//  CUAdminFacturas.cs
//  Clase de implementación de CUAdminFacturas.
//  Generated by Fito
//  Created on:      08-abr-2009 11:32:54
//  Original author: Fito
///////////////////////////////////////////////////////////
using scioControlLibrary;
using scioControlLibrary.enums;
using scioControlLibrary.interfaces;
using sgmpro.dominio.caja;

namespace cuAbmFactura {
    public class CUAdminFacturas : CUAdminGenerico<Factura> {
        /// <summary>
        /// Este métodor retorna el controlador a utilizarse. Es para 
        /// sobrepasar en una clase heredada y establecer el controlador 
        /// correcto.
        /// </summary>
        /// <returns>
        /// El controlador que debe utilizarse para este list-preview.
        /// </returns>
        protected override IControladorPreview<Factura> getControlador() {
            return new CUListFacturas { ModoVista = EModoVentana.LIST };
        }
    }
}