///////////////////////////////////////////////////////////
//  EOperadorLogUnario.cs
//  Implementation of the Class EOperadorLogUnario
//  Generated by Enterprise Architect
//  Created on:      13-abr-2009 17:23:40
//  Original author: Fito
///////////////////////////////////////////////////////////
namespace scioPersistentLibrary.enums {
    /// <summary>
    /// Enumeración que contiene los distintos operadores logicos unarios
    /// que pueden utilizarse dentro de los criterios de consulta.
    /// </summary>
    public enum EOperadorLogUnario {
        NOT = 0
    }
}