///////////////////////////////////////////////////////////
//  EOperadorSimple.cs
//  Implementation of the Class EOperadorSimple
//  Generated by Enterprise Architect
//  Created on:      13-abr-2009 17:23:40
//  Original author: Fito
///////////////////////////////////////////////////////////
namespace scioPersistentLibrary.enums {
    /// <summary>
    /// Enumeración que contiene los distintos operadores simples binarios
    /// que pueden utilizarse dentro de los criterios de consulta.
    /// </summary>
    public enum EOperadorSimple {
        IGUAL = 0,
        MENORQUE,
        MENORIGUAL,
        MAYORQUE,
        MAYORIGUAL,
        DISTINTO,
        LIKE
    }
}
