///////////////////////////////////////////////////////////
//  ETipoParametro.cs
//  Implementation of the Class ETipoParametro
//  Generated by Enterprise Architect
//  Created on:      13-abr-2009 17:23:40
//  Original author: Fito
///////////////////////////////////////////////////////////
namespace scioPersistentLibrary.enums {
    /// <summary>
    /// Enumeración que contiene los distintos tipos de parámetros
    /// que pueden existir dentro del sistema. El tipo de un parámetro
    /// es un valor que permite agrupar lógicamente distintos valores
    /// en base a un criterio común y/o para ser utilizados en un 
    /// entorno común y fijo (por ejemplo: por parámetros tipo MENU
    /// son lo que se usan para armar la raiz del menu principal del 
    /// sistema).
    /// </summary>
    public enum ETipoParametro {
        NINGUNO = 0,
        BASE,
        RECURSO,
        MENU,
        SUBMENU,
        TRIMENU,
        GESTION       
    }
}