///////////////////////////////////////////////////////////
//  CUAbmEjecucion.cs
//  Clase de implementación de CUAbmEjecucion.
//  Generated by Fito
//  Created on:      08-abr-2009 11:32:54
//  Original author: Fer
///////////////////////////////////////////////////////////
using System.Drawing;
using cuGenerarJobs.Properties;
using scioControlLibrary;
using sgmpro.dominio.scheduler;

namespace cuGenerarJobs {
    /// <summary>
    ///   Caso de Uso que configura y genera jobs.
    /// </summary>
    public class CUAbmEjecucion : CUAbmGenerico<Ejecucion> {
        #region IControladorEditable Members
        /// <summary>
        ///   Implementación del método de la interfaz.
        /// </summary>
        public override PanelABMV<Ejecucion> crearPanelEdicion() {
            return new PanelAbmvExes(this);
        }

        /// <summary>
        ///   Implementación del método de la interfaz.
        /// </summary>
        public override Icon getIcono() {
            return Resources.clockplay;
        }

        /// <summary>
        ///   Implementación del método de la interfaz.
        /// </summary>
        public override void verify(params object[] parametros) {}
        #endregion
    }
}