///////////////////////////////////////////////////////////
//  CUEditarJob.cs
//  Clase de implementación de CUEditarJob.
//  Generated by Fito
//  Created on:      08-abr-2009 11:32:54
//  Original author: Fer
///////////////////////////////////////////////////////////
using scioControlLibrary;
using scioControlLibrary.enums;
using scioControlLibrary.interfaces;
using sgmpro.dominio.scheduler;

namespace cuGenerarJobs {
    public class CUEditarJob : CUAdminGenerico<Job> {
        /// <summary>
        /// Este métodor retorna el controlador a utilizarse. Es para sobrepasar
        /// en una clase heredada y establecer el controlador correcto.
        /// </summary>
        /// <returns>
        /// El controlador que debe utilizarse para este list-preview.
        /// </returns>
        protected override IControladorPreview<Job> getControlador() {
            return new CUListJobs {ModoVista = EModoVentana.LIST};
        }
    }
}