///////////////////////////////////////////////////////////
//  CUListJobs.cs
//  Clase de implementación de CUListJobs.
//  Generated by Fito
//  Created on:      08-abr-2009 11:32:54
//  Original author: Fer
///////////////////////////////////////////////////////////
using System.Drawing;
using cuGenerarJobs.Properties;
using scioControlLibrary;
using scioPersistentLibrary.orden;
using scioToolLibrary;
using sgmpro.dominio.scheduler;

namespace cuGenerarJobs {
    /// <summary>
    ///   Esta clase hereda de CUListGenerico y se encarga de 
    ///   gestionar un PanelListABMV para la entidad JobGenListaGestion.
    /// </summary>
    public class CUListJobs : CUPreviewGenerico<Job> {
        /// <summary>
        ///   Constructor de la Direction que inicializa elementos internos.
        /// </summary>
        public CUListJobs() {
            ControlEditable = new CUAbmJob();
            ColsInvisibles.Add("Listas");
            ColsInvisibles.Add("Ejecuciones");
            Ordenamiento.Add(Orden.Desc("Ultima"));
        }

        #region IControladorPreview
        /// <summary>
        ///   Implementación del método de la interfaz.
        /// </summary>
        public override string getTitulo() {
            return Mensaje.TextoMensaje("TITULO-ABMV-JOBGES");
        }

        /// <summary>
        ///   Implementación del método de la interfaz.
        /// </summary>
        public override Icon getIcono() {
            return Resources.clockplay;
        }
        #endregion

        #region IControladorListable Members
        /// <summary>
        ///   Implementación del método de la interfaz.
        /// </summary>
        protected override PanelListABMV<Job> crearPanelListado() {
            return new PanelListJobs(this);
        }

        /// <summary>
        ///   Implementación del método de la interfaz.
        /// </summary>
        protected override PanelPreview<Job> crearPanelPreview() {
            return new PanelPreviewJob(ControlEditable);
        }
        #endregion
    }
}