///////////////////////////////////////////////////////////
//  CUAdminParametros.cs
//  Clase de implementación de CUAdminParametros.
//  Generated by Fito
//  Created on:      08-abr-2009 11:32:54
//  Original author: Fito
///////////////////////////////////////////////////////////
using scioControlLibrary;
using scioControlLibrary.enums;
using scioControlLibrary.interfaces;
using scioParamLibrary.dominio;

namespace cuAbmParametro {
    public class CUAdminParametros : CUAdminGenerico<Parametro> {
        /// <summary>
        /// Este métodor etorna el controlador a utilizarse. Es para sobrepasar
        /// en una clase heredada y establecer el controlador correcto.
        /// </summary>
        /// <returns>
        /// El controlador que debe utilizarse para este list-preview.
        /// </returns>
        protected override IControladorPreview<Parametro> getControlador() {
            return new CUListParametros {ModoVista = EModoVentana.LIST};
        }
    }
}