///////////////////////////////////////////////////////////
//  TipoConvenio.cs
//  Implementation of the Class TipoConvenio
//  Generated by Enterprise Architect
//  Created on:      20-Sep-2009 16:57:17
//  Original author: Fito
///////////////////////////////////////////////////////////
using scioPersistentLibrary.acceso;

namespace sgmpro.dominio.configuracion {
    public class TipoConvenio : EntidadIdentificada<TipoConvenio> {
        /// <summary>
        /// Nombre del convenio. (utilizado en la aplicación). No Nulo.
        /// </summary>
        public virtual string Nombre { get; set; }
        /// <summary>
        /// Descripción del convenio (utilizado en la aplicación). No Nulo.
        /// </summary>
        public virtual string Descripcion { get; set; }
        /// <summary>
        /// La cantidad mínima de cuotas que se permiten para el convenio. No Nulo.
        /// </summary>
        public virtual long MinCuotas { get; set; }
        /// <summary>
        /// La cantidad máxima de cuotas que se permiten para el convenio. No Nulo.
        /// </summary>
        public virtual long MaxCuotas { get; set; }
        /// <summary>
        /// La cantidad máxima de cuotas que se permiten caer. No Nulo.
        /// </summary>
        public virtual long MaxCuotasCaidas { get; set; }
        /// <summary>
        /// El valor mínimo para los anticipos del convenio. No Nulo.
        /// </summary>
        public virtual double ValorMinimoAnticipo { get; set; }
        /// <summary>
        /// El valor mínimo para las cuotas del convenio. No Nulo.
        /// </summary>
        public virtual double ValorMinimoCuota { get; set; }
        /// <summary>
        /// El valor máximo de quita (% sobre interes origen) del convenio. No Nulo.
        /// </summary>
        public virtual double MaxQuita { get; set; }
        /// <summary>
        /// Si permite generar convenios de este tipo. No Nulo.
        /// </summary>
        public virtual bool Activo { get; set; }
        /// <summary>
        /// La tasa de interés del cálculo. No Nulo.
        /// </summary>
        public virtual double TasaPura { get; set; }
        /// <summary>
        /// Si aplica el IVA a la tasa de interes. No Nulo.
        /// </summary>
        public virtual bool IVAsobreTP { get; set; }
        /// <summary>
        /// El interés punitorio para las cuotas del convenio. No Nulo.
        /// </summary>
        public virtual double Punitorio { get; set; }
        /// <summary>
        /// El porcentaje de honorarios para el calculo de actualizacion de las cuotas del convenio. No Nulo.
        /// </summary>
        public virtual double Honorarios { get; set; }
        /// <summary>
        /// Regla de Calculo del Anticipo Base del Convenio (>0 es H = %(A-GA) ó 0 es que H = GA). No Nulo.
        /// </summary>
        public virtual double ReglaHA { get; set; }
        /// <summary>
        /// Fórmula para el cálculo de gastos. No Nulo.
        /// </summary>
        public virtual string FormulaBaseConvenio { get; set; }
        /// <summary>
        /// Fórmula para el cálculo de la cuota total. No Nulo.
        /// </summary>
        public virtual string FormulaCuota { get; set; }
        /// <summary>
        /// Fórmula para el cálculo de intereses. No Nulo.
        /// </summary>
        public virtual string FormulaInteres { get; set; }
        /// <summary>
        /// Fórmula para el cálculo de honorarios. No Nulo.
        /// </summary>
        public virtual string FormulaHonorarios { get; set; }
        /// <summary>
        /// Fórmula para el cálculo de gastos. No Nulo.
        /// </summary>
        public virtual string FormulaGastos { get; set; }

        /// <summary>
        /// Este método genera el string por defecto a mostrar en todos lados.
        /// </summary>
        public override string ToString() {
            return Nombre;
        }
    }
}