///////////////////////////////////////////////////////////
//  Variable.cs
//  Implementation of the Class Variable
//  Generated by Enterprise Architect
//  Created on:      20-abr-2009 18:14:40
//  Original author: Fernando
///////////////////////////////////////////////////////////
using scioPersistentLibrary.acceso;
using sgmpro.interfases;

namespace sgmpro.dominio.configuracion {
    /// <summary>
    /// Expresión que representa un valor de usuario que se utilizará dentro de un
    /// Predicado. El valor de la Variable se reemplaza en el procesamiento del
    /// Predicado por un valor de tabla.
    /// </summary>
    public class Variable : EntidadIdentificada<Variable>, IExpresion {
        /// <summary>
        /// Nombre
        /// </summary>
        public virtual string Nombre { get; set; }
        /// <summary>
        /// Descripcion
        /// </summary>
        public virtual string Descripcion { get; set; }
        /// <summary>
        /// Valor
        /// </summary>
        public virtual string Valor { get; set; }

        /// <summary>
        /// Este método genera el string por defecto a mostrar en todos lados.
        /// </summary>
        public override string ToString() {
            return string.Format("{0} ({1})", Nombre, Valor);
        }
    }
}