///////////////////////////////////////////////////////////
//  SgmproRelacional.cs
//  Clase de generación de cadenas del consultas relacionales
//  Generated by Fito
//  Created on:      08-abr-2009 11:32:54
//  Original author: Fito
///////////////////////////////////////////////////////////
using scioPersistentLibrary.interfases;

namespace sgmpro {
    public class SgmproRelacional : IHelperRelacional {
        /// <summary>
        /// Este método debería devolver el prefijo para campos de la tabla,
        /// de manera de que el nomreb de cada campo de la tabla, en la base 
        /// de datos, se pueda armar con este prefijo + guinbajo + el nombre 
        /// del atributo dentro de la clase.
        /// </summary>
        public string getPrefijo(string tabla) {
            switch (tabla.ToUpper()) {
                case "PAGO":
                    return "pag";
                case "GESTION":
                    return "ges";
                case "DEUDA":
                    return "deu";
                case "CUENTA":
                    return "cta";
                case "PERSONA":
                    return "prs";
                default:
                    return string.Empty;
            }
        }

        /// <summary>
        /// Este método debería devolver la lista de campos del select, con
        /// todos los campos y los nombres que se desean mostrar en un listado.
        /// </summary>
        public string getSelectString(string tabla) {
            switch (tabla.ToUpper()) {
                case "CUENTA":
                    return "select cta_id as Id"
                           + ",(select ent_nombre+' ('+ent_cuit+')' from entidad where ent_id = cta_entidad) as Entidad"
                           + ",(select pro_codigo+': '+pro_nombre+')' from producto where pro_id = cta_producto) as Prodcuto"
                           + ",cta_codigo as Codigo"
                           + ",cta_descripcion as Descripcion"
                           + ",(select prs_nombre+' - '+prs_dni from persona where prs_id = cta_titular) as Titular"
                           + ",(select prs_nombre+' - '+prs_dni from persona where prs_id = cta_garante) as Garante"
                           + ",(select par_nombre from parametro where par_id = cta_estado) as EstadoCivil"
                           + ",cta_expediente as Expediente"
                           + ",cta_legales as Legales"
                           + ",cta_activada as Activada"
                           + ",cta_vigencia as Vigencia"
                           + ",(select usu_nombre from usuario where usu_id = cta_gestor) as Gestor"
                           + ",(select lge_nombre+' ('+convert(varchar,lge_fchcreacion,121)+')' from listagestion where lge_id = cta_listaasignada) as ListaAsignada"
                           + ",(select (select par_nombre from parametro where par_id = cvn_tipo)+' ('+convert(varchar,cvn_fechaalta,121)+')' from convenio where cvn_id = cta_convenioactivo) as ConvenioActivo"
                           + ",cta_fechaelegible as FechaElegible"
                           + ",cta_fechaalta as FechaAlta"
                           + ",cta_fechaasignacion as FechaAsignacion"
                           + " from Cuenta where ";
                case "DEUDA":
                    return "select deu_id as Id"
                           + ",deu_fechavto as FechaVto"
                           + ",deu_fechabaja as FechaBaja"
                           + ",deu_informada as Informada"
                           + ",(select par_nombre from parametro where par_id = deu_concepto) as Concepto"
                           + ",(select par_nombre from parametro where par_id = deu_detalle) as Detalle"
                           + ",deu_descripcion as Descripcion"
                           + ",(select par_nombre from parametro where par_id = deu_estado) as Estado"
                           + ",(deu_capital+deu_interes+deu_honorarios+deu_gastos) as Total"
                           + ",deu_capital as Capital"
                           + ",deu_interes as Interes"
                           + ",deu_honorarios as Honorarios"
                           + ",deu_gastos as Gastos"
                           + ",(select cta_codigo+' ('+(select prs_nombre+' - '+prs_dni from persona where prs_id = cta_titular)+')' from cuenta where cta_id = deu_cuenta) as Cuenta"
                           + ",(select (select par_nombre from parametro where par_id = cvn_tipo)+' ('+convert(varchar,cvn_fechaalta,121)+')' from convenio where cvn_id = deu_convenio) as Convenio"
                           + ",deu_cuota as Cuota"
                           + ",deu_capitalo as CapitalO"
                           + ",deu_intereso as InteresO"
                           + ",deu_honoro as HonorO"
                           + ",deu_gastoso as GastosO"
                           + " from Deuda where";
                case "PAGO":
                    return "select pag_id as Id"
                           + ",pag_fecha as Fecha"
                           + ",(select par_nombre from parametro where par_id = pag_tipo) as Tipo"
                           + ",(select par_nombre from parametro where par_id = pag_estado) as Estado"
                           + ",pag_descripcion as Descripcion"
                            //////////////////////////////////////////////////////////////
                            // MODIFICADO POR FITO EL 03/11/2013:                       //
                            // Para que no muestre No.0 en recibos de tipo NINGNO o en  //
                            // cualquie otr caso que no tenga numero.                   //
                            //////////////////////////////////////////////////////////////
                           + ",(select top 1 (par_nombre+(case when rec_numero is not null and rec_numero!='0'then(+' Nº '+rec_numero)else ''end)) from recibo, parametro where rec_tipo = par_id and rec_fechabaja = convert(datetime, '1753-01-01 00:00:00.000', 121) and rec_pago = pag_id) as Recibo"
                            //////////////////////////////////////////////////////////////
                           + ",(pag_capital+pag_interes+pag_honorarios+pag_gastos) as Total "
                           + ",pag_capital as Capital"
                           + ",pag_interes as Interes"
                           + ",pag_honorarios as Honorarios"
                           + ",pag_gastos as Gastos"
                           + ",(select par_nombre from parametro where par_id = pag_formapago) as FormaPago"
                           + ",(select cta_codigo+' ('+(select prs_nombre+' - '+prs_dni from persona where prs_id = cta_titular)+')' from cuenta where cta_id = pag_cuenta) as Cuenta"
                           + ",pag_fechaumod as FechaUMod"
                           + " from Pago where";
                case "GESTION":
                    return "select ges_id as Id"
                           + ",(select cta_codigo+' ('+(select prs_nombre+' - '+prs_dni from persona where prs_id = cta_titular)+')' from cuenta where cta_id = ges_cuenta) as Cuenta"
                           + ",ges_fechainicio as FechaInicio"
                           + ",(select par_nombre from parametro where par_id = ges_tipo) as Tipo"
                           + ",(select par_nombre from parametro where par_id = ges_resultado) as Resultado"
                           + ",ges_resultadodesc as ResultadoDesc"
                           + ",ges_resultadofecha as ResultadoFecha"
                           + ",(select par_nombre from parametro where par_id = ges_estado) as Estado"
                           + ",ges_fechacierre as FechaCierre"
                           + ",(select usu_nombre from usuario where usu_id = ges_usuario) as Usuario"
                           + ",(select prs_nombre+' ('+prs_dni+')' from persona where prs_id = ges_contactado) as Contactado"
                           + ",(select (select par_nombre from parametro where par_id = con_tipo)+' ('+con_descripcion+')' from contacto where con_id = ges_contacto) as Contacto"
                           + ",ges_fechaanulacion as FechaAnulacion"
                           + ",ges_fechaumod as FechaUMod"
                           + " from Gestion where";
                case "PERSONA":
                    return "select prs_id as Id"
                           + ",prs_nombre as Nombre"
                           + ",prs_dni as DNI"
                           + ",prs_cuit as Cuit"
                           + ",(select par_nombre from parametro where par_id = prs_tipoiva) as TipoIVA"
                           + ",(select par_nombre from parametro where par_id = prs_estadocivil) as EstadCivil"
                           + ",(select par_nombre from parametro where par_id = prs_sexo) as Sexo"
                           + ",prs_profesion as Profesion"
                           + ",prs_trabajo as Trabajo"
                           + ",(select par_nombre from parametro where par_id = prs_economia) as Economia"
                           + ",prs_comentario as Comentario"
                           + ",prs_fechaumod as FechaUMod"
                           + " from Persona";
                default:
                    return "*";
            }
        }
    }
}