///////////////////////////////////////////////////////////
//  CriterioConsulta.cs
//  Implementation of the Class CriterioConsulta
//  Generated by Enterprise Architect
//  Created on:      13-abr-2009 17:23:40
//  Original author: Fito
///////////////////////////////////////////////////////////
using NHibernate.Criterion;
using scioPersistentLibrary.enums;
using scioPersistentLibrary.interfases;

namespace scioPersistentLibrary.orden {
    /// <summary>
    /// Esta es la clase base de la jerarquía que implementa, vía la interfase
    /// IOrdenConsulta, el concepto de un criterio de ordenamiento de consulta 
    /// abstraído de la capa de peristencia real del sistema, permitiendo hacia 
    /// abajo utilizar distintos mecanismos.
    /// </summary>
    public class Orden : IOrdenConsulta {
        protected string _atributo;
        protected EOperadorOrden _op;

        /// <summary>
        /// Constructor de la clase para una expresion de ordenamiento.
        /// </summary>
        protected Orden(EOperadorOrden orden, string atributo) {
            _atributo = atributo;
            _op = orden;
        }

        #region Implementation of IOrdenConsulta
        public virtual string getOrdenSQL() {
            return getOrdenSQL(null);
        }

        /// <summary>
        /// Implementción del método de la interfaz.
        /// </summary>
        public virtual string getOrdenSQL(string prefijo) {
            string pre = (prefijo != null) ? prefijo + "_" : "";
            return (_op == EOperadorOrden.ASC)
                ? string.Format("{0}{1} asc", pre, _atributo)
                : string.Format("{0}{1} desc", pre, _atributo);
        }

        /// <summary>
        /// Implementción del método de la interfaz.
        /// </summary>
        public virtual Order getOrdenNH() {
            return (_op == EOperadorOrden.ASC)
                ? Order.Asc(_atributo)
                : Order.Desc(_atributo);
        }
        #endregion

        #region helpers
        /// <summary>
        /// Método que encapsula la creación de un IOrdenConsulta.
        /// </summary>
        public static Orden Asc(string atributo) {
            return new Orden(EOperadorOrden.ASC, atributo);
        }

        /// <summary>
        /// Método que encapsula la creación de un IOrdenConsulta.
        /// </summary>
        public static Orden Desc(string atributo) {
            return new Orden(EOperadorOrden.DESC, atributo);
        }
        #endregion
    }
}