///////////////////////////////////////////////////////////
//  LogErrorException.cs
//  Implementation of the Class LogErrorException
//  Generated by Enterprise Architect
//  Created on:      14-abr-2009 19:39:46
//  Original author: Fito
///////////////////////////////////////////////////////////
using scioToolLibrary.excepciones;

namespace scioLoggingLibrary.excepciones {
    /// <summary>
    /// Esta clase de excepción debe utilizarse para representar todos
    /// los errores asociados a un problema con el servicio de logging 
    /// del sistema.
    /// </summary>
    public class LogErrorException : ScioErrorException {
        public LogErrorException(string mensaje) : base(mensaje) {}
        public LogErrorException(string mensaje, string extra) : base(mensaje, extra) {}
    }
}