///////////////////////////////////////////////////////////
//  IControladorWinList.cs
//  Implementation of the Interface IControladorWinList
//  Generated by Enterprise Architect
//  Created on:      15-Abr-2009 07:11:10 p.m.
//  Original author: Fito
///////////////////////////////////////////////////////////
namespace scioControlLibrary.interfaces {
    /// <summary>
    ///   Interfase que representa el comportamiento deseado para el controlador de
    ///   una ventana WinListConAccionExtra, de manera de implementar la forma de responder a la
    ///   accion extra de WinListConAccionExtra.
    /// </summary>
    public interface IControladorWinList {
        /// <summary>
        ///   Este método es el encargado de retornar el nombre de la
        ///   acción extra del WinListConAccionExtra que sera llamada cuando se hace
        ///   click en el boton de acción extra.
        /// </summary>
        /// <returns>
        ///   El nombre de la acción extra.
        /// </returns>
        string getNombreAccionExtra();

        /// <summary>
        ///   Este método es el encargado de ejecutar la accion extra de 
        ///   la venatana WinListConAccionExtra al hacer click en el boton de acción extra.
        /// </summary>
        /// <param name = "parametros">
        ///   Un vararg que acepta parametros que puedan necesitarse.
        /// </param>
        void ejecutarAccion(params object[] parametros);
    }
}