///////////////////////////////////////////////////////////
//  IPublicWinAbmv.cs
//  Implementation of the Interface IPublicWinAbmv
//  Generated by Enterprise Architect
//  Created on:      15-Abr-2009 07:11:10 p.m.
//  Original author: Fernando
///////////////////////////////////////////////////////////
using System.Windows.Forms;

namespace scioControlLibrary.interfaces {
    /// <summary>
    /// Interfase que representa el comportamiento público generico deseable 
    /// de una clase que implementa una ventana y que contiene un panel para 
    /// la edición ABMV (agregar, borrar, modificar, ver) de una entidad del 
    /// sistema.
    /// </summary>
    public interface IPublicWinAbmv {
        /// <summary>
        /// Este método establece el modo en que se visualiza
        /// la ventana (qué botones se muestran) de acuerdo al
        /// modo de vista del controlador asociado.
        /// </summary>
        void setModoVista();

        /// <summary>
        /// Este método permite guardar los datos del panel sin la
        /// necesidad de cerrar la ventana (como se hace cuando se
        /// graba vía el botón del menú) y es para los casos en que 
        /// se quiere agregar un nuevo registro en un listado detail 
        /// de un panelABMV y todavía no se grabó el master que se 
        /// está agregando.
        /// </summary>
        void guardarDatos();

        /// <summary>
        /// Este método es el encargado de devolver el componente
        /// visula padre del panel (el Parent), el que normalmente
        /// es un IPublicWinAbmv u otro contenedor.
        /// </summary>
        ContainerControl getParent();
    }
}
