///////////////////////////////////////////////////////////
//  CUBandejaEntrada.cs
//  Clase de control para la ventana de bandeja de entrada.
//  Generated by Fito
//  Created on:      08-abr-2009 11:32:54
//  Original author: Fito
///////////////////////////////////////////////////////////
using System;
using System.Windows.Forms;
using scioBaseLibrary;
using scioBaseLibrary.excepciones;
using scioControlLibrary;
using scioToolLibrary.enums;

namespace cuBandejaEntrada {
    public class CUBandejaEntrada : CUConfigurarGenerico<BandejaEntradaTree> {
        #region Implementation of IControladorCasoUso
        /// <summary>
        /// Implementación del método de la interfaz.
        /// </summary>
        public override bool iniciar(object padre, params object[] valor) {
            try {
                // Controla que el padre sea de un tipo válido
                if (!(padre is Form))
                    return false;
                Padre = padre;

                // Obtiene y acepta los parametros de entrada
                aceptarParametros(valor);

                // Crea y abre la ventana de configuracion
                (new WinBandejaEntrada(new BandejaEntradaTree()) {
                    StartPosition = FormStartPosition.CenterScreen,
                    MdiParent = ((Form) Padre)
                }).Show();

                // Si termina está ok, entonces retorna true
                return true;
            } catch (Exception e) {
                Sistema.Controlador.logear("UCCALLER-NOINIT", ENivelMensaje.ERROR, e.ToString());
                throw new AppErrorException("UCCALLER-NOINIT");
            }
        }
        #endregion
    }
}