///////////////////////////////////////////////////////////
//  ListasGestion.cs
//  Implementation of the Class ListasGestion
//  Generated by Enterprise Architect
//  Created on:      13-May-2009 03:55:00 p.m.
//  Original author: Fito
///////////////////////////////////////////////////////////
using System.Collections.Generic;
using scioPersistentLibrary.acceso;
using scioPersistentLibrary.criterios;
using scioPersistentLibrary.orden;

namespace sgmpro.dominio.configuracion.repos {
    ///<summary>
    /// Persistencia de la clase ListaGestion
    ///</summary>
    public class ListasGestion : RepositorioPersistente<ListaGestion> {
        /// <summary>
        /// Este método devuelve un listado de las listas de gestion vivas
        /// según su cuenta si poseen un determinado tipo de lista de gestión
        /// ordenadas por fecha de creacion en forma descendente (primero las
        /// mas nuevas).
        /// </summary>
        /// <param name="tipo">
        /// El tipo de lista de gestión del que se desean las listas vivas.
        /// </param>
        /// <returns>
        /// El listado de listas de gestion vivas que tienen el tipo deseado
        /// ordenadas por fecha de creacion en forma descendente (primero las
        /// mas nuevas).
        /// </returns>
        public static IList<ListaGestion> GetAliveByTipo(TipoListaGestion tipo) {
            return GetByCriteria(
                true,
                new[] {Criterios.Igual("TipoLista", tipo)},
                new[] {Orden.Desc("FchCreacion")});
        }
    }
}