///////////////////////////////////////////////////////////
//  CUAbmTipoLista.cs
//  Clase de implementación de CUAbmTipoLista.
//  Generated by Fito
//  Created on:      08-abr-2009 11:32:54
//  Original author: Fito
///////////////////////////////////////////////////////////
using scioBaseLibrary.excepciones;
using scioControlLibrary;
using scioToolLibrary;
using sgmpro.dominio.configuracion;

namespace cuAbmTipoLista {
    /// <summary>
    /// Esta clase hereda de CUAbmGenerico y se encarga de gestionar la 
    /// ventana WinABMV junto con su panelABMV para la entidad TipoListaGestion.
    /// </summary>
    public class CUAbmTipoLista : CUAbmGenerico<TipoListaGestion> {
        #region IControladorEditable
        /// <summary>
        /// Implementación del método de la interfaz.
        /// </summary>
        public override PanelABMV<TipoListaGestion> crearPanelEdicion() {
            return new PanelAbmvTipoLista(this);
        }

        /// <summary>
        /// Implementación del método de la interfaz.
        /// </summary>
        public override void verify(params object[] parametros) {
            if (string.IsNullOrEmpty(ObjetoEnEdicion.Descripcion))
                throw new DataErrorException("CAMPO-NOK", Mensaje.TextoValidacion("TIPOLISTA-DESC"));

            if (string.IsNullOrEmpty(ObjetoEnEdicion.Nombre))
                throw new DataErrorException("CAMPO-NOK", Mensaje.TextoValidacion("TIPOLISTA-NOMBRE"));

            if (ObjetoEnEdicion.Perfil == null)
                throw new DataErrorException("CAMPO-NOK", Mensaje.TextoValidacion("TIPOLISTA-PERFIL"));

            if (ObjetoEnEdicion.Prioridad < 0 || ObjetoEnEdicion.Prioridad > 10)
                throw new DataErrorException("CAMPO-NOK", Mensaje.TextoValidacion("TIPOLISTA-PRIORIDAD"));
        }

        /// <summary>
        /// Implementación del método de la interfaz.
        /// </summary>
        public override string getTitulo() {
            return Mensaje.TextoMensaje("TITULO-ABMV-TIPOLISTA");
        }
        #endregion
    }
}