///////////////////////////////////////////////////////////
//  CUListCuotas.cs
//  Clase de implementación de CUListCuotas.
//  Generated by Fito
//  Created on:      08-abr-2009 11:32:54
//  Original author: Fito
///////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Windows.Forms;
using cuAbmDeuda;
using scioBaseLibrary.excepciones;
using scioControlLibrary;
using scioControlLibrary.enums;
using scioPersistentLibrary.orden;
using scioToolLibrary;
using sgmpro.dominio.configuracion;
using sgmpro.dominio.configuracion.repos;

namespace cuAbmConvenio {
    /// <summary>
    /// Esta clase hereda de CUListGenerico y se encarga de 
    /// gestionar un PanelListABMV para la entidad Deuda para
    /// cutoas de un convenio.
    /// </summary>
    public class CUListCuotas : CUListGenerico<Deuda> {
        /// <summary>
        /// Constructor de la clase que inicializa elementos internos.
        /// </summary>
        public CUListCuotas() {
            ControlEditable = new CUAbmDeuda();
            ColsInvisibles.Add("Cuenta");
            ColsInvisibles.Add("Convenio");
            ColsInvisibles.Add("CapitalO");
            ColsInvisibles.Add("InteresO");
            ColsInvisibles.Add("HonorO");
            ColsInvisibles.Add("GastosO");
            Ordenamiento.Add(Orden.Asc("FechaVencimiento"));
        }

        #region IControladorListable Members
        /// <summary>
        /// Implementación del método de la interfaz.
        /// </summary>
        public override PanelListABMV<Deuda> getPanelListado(params object[] parametros) {
            return base.getPanelListado(EModoVentana.VIEW);
        }

        /// <summary>
        /// Implementación del método de la interfaz.
        /// </summary>
        public override BindingSource listList(params object[] parametros) {
            try {
                _bs = _bs ?? new BindingSource();

                // Ejecuta el filtro y obtiene resultados desde el objeto 
                // en memoria (porque se podria estar probando la generacion)
                if (ObjetoMaster is Convenio) {
                    _bs = new BindingSource {
                        DataSource = CollectionHelper
                            .ConvertTo(Deudas.OrdenarPorFecha(((Convenio)ObjetoMaster).Cuotas))
                    };

                    // Obtiene la cantidad de registros para mostrar
                    Cuenta = ((DataTable)_bs.DataSource).Rows.Count;

                    // Retorna el bs creado
                    return _bs;
                }

                Cuenta = 0;
                return _bs;
            } catch (Exception e) {
                throw new VistaErrorException("DATA-LISTNOK", e.ToString());
            }
        }
        #endregion
    }
}