///////////////////////////////////////////////////////////
//  CUListConvenios.cs
//  Clase de implementación de CUListConvenios.
//  Generated by Fito
//  Created on:      08-abr-2009 11:32:54
//  Original author: Fito
///////////////////////////////////////////////////////////
using scioBaseLibrary;
using scioControlLibrary;
using scioPersistentLibrary.criterios;
using scioPersistentLibrary.interfases;
using scioPersistentLibrary.orden;
using scioToolLibrary.enums;
using sgmpro.dominio.configuracion;

namespace cuAbmConvenio {
    /// <summary>
    /// Esta clase hereda de CUListGenerico y se encarga de 
    /// gestionar un PanelListABMV para la entidad Convenio.
    /// </summary>
    public class CUListConvenios : CUPreviewGenerico<Convenio> {
        /// <summary>
        /// Constructor de la clase que inicializa elementos internos.
        /// </summary>
        public CUListConvenios() {
            ControlEditable = new CUAbmConvenio();
            ColsInvisibles.Add("Cuotas");
            Ordenamiento.Add(Orden.Asc("FechaAlta"));
        }

        #region IControladorListable Members
        /// <summary>
        /// Implementación del método de la interfaz.
        /// </summary>
        protected override PanelPreview<Convenio> crearPanelPreview() {
            return new PanelPreviewConvenio(ControlEditable);
        }

        /// <summary>
        /// Implementación del método de la interfaz.
        /// </summary>
        public override void listAdd(params object[] parametros) {
            Sistema.Controlador.mostrar("ERROR-ADD-CONVENIO", ENivelMensaje.INFORMACION, null, false);
        }

        /// <summary>
        /// Implementación del método de la interfaz.
        /// </summary>
        public override ICriterioConsulta getFiltroMaster() {
            if (ObjetoMaster is Cuenta)
                return Criterios.Igual("Cuenta", ObjetoMaster);

            return base.getFiltroMaster();
        }
        #endregion
    }
}